### ISSUE TITLE
String Reverse Karne Par Gadbadi Ho Rahi Hai

### ISSUE THREAD

**Issue by 80bit23** [vtcbca/basic-programming-80bit23#2]
string ko reverse kar raha hoon, lekin output kuch samajh nahi aa raha.

**Comment by 7bit23** [comment]
nayi string banane ki jagah purani wali ko badal rahe ho kya?

**Comment by 80bit23** [comment]
Matlab nayi string banani padegi?

**Comment by 7bit23** [comment]
ha purani ko hi badalne ki koshish mat lar, vo rahene de

**Comment by 80bit23** [comment]
Samajh gaya! Ulti karte waqt nayi string mein daalna padega. Ab sahi chal raha hai. Shukriya!
